# Generated by Django 3.1.7 on 2021-03-14 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='date_offer',
        ),
        migrations.AlterField(
            model_name='listing',
            name='balcony',
            field=models.BooleanField(default=False, verbose_name='Наличие балкона'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='ceiling_height',
            field=models.FloatField(null=True, verbose_name='Высота потолков'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(max_length=200, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='company_construction',
            field=models.CharField(max_length=200, null=True, verbose_name='Строительная компания'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='district',
            field=models.CharField(max_length=200, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='floor',
            field=models.IntegerField(verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='floors_number',
            field=models.IntegerField(null=True, verbose_name='Этажность дома'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='house_number',
            field=models.CharField(max_length=200, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Выставлен на продажу'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='kitchen_area',
            field=models.IntegerField(null=True, verbose_name='Площадь кухни'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='material',
            field=models.CharField(max_length=200, null=True, verbose_name='Материал дома'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_1',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_2',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_3',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_4',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_5',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_6',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='residental_area',
            field=models.IntegerField(null=True, verbose_name='Площадь жилая'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='street',
            field=models.CharField(max_length=200, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='total_area',
            field=models.IntegerField(verbose_name='Общая площадь в м^2'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='year_construction',
            field=models.IntegerField(null=True, verbose_name='Год постройки дома'),
        ),
    ]
