# Generated by Django 3.1.7 on 2021-03-14 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20210314_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='ceiling_height',
            field=models.FloatField(blank=True, null=True, verbose_name='Высота потолков'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='company_construction',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Строительная компания'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='floors_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Этажность дома'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='kitchen_area',
            field=models.IntegerField(blank=True, null=True, verbose_name='Площадь кухни'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='material',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Материал дома'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_6',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='residental_area',
            field=models.IntegerField(blank=True, null=True, verbose_name='Площадь жилая'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='year_construction',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год постройки дома'),
        ),
    ]
