# Generated by Django 3.1.7 on 2021-05-15 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.CharField(max_length=200, verbose_name='Недвижимость')),
                ('listing_id', models.IntegerField(verbose_name='ID недвижимости')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('email', models.CharField(max_length=100, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата заявки')),
            ],
        ),
    ]
